MathWhiteboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('whiteboard.urls')),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, include
from .views.other_views import index

app_name = "accounts"
urlpatterns = [
    path("", index, name="index"), # Home page
    path("", include("accounts.urls_folder.friends_urls")),
    path("", include("accounts.urls_folder.registration_urls")),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    {% csrf_token %}
    {% block body %}{% endblock %}
</body>
</html>

templates/base_with_header_menu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <script src="{% static 'js/menu.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
    {% csrf_token %}
    {% include 'menu.html' %}
    {% block body %}{% endblock %}
</body>
</html>

templates/menu.html
<header>
    <nav>
        <div id="header_left_menu">
            <button id="home_button" class="header_menu_button" data-url="{% url 'accounts:index' %}">Home</button>
            <button id="my_boards_button" class="header_menu_button">My Boards</button>
        </div>
        <div id="header_right_menu">
            <button id="friend_search_button" data-url="{% url 'accounts:friend_search' %}" class="header_menu_button">Friends</button>
            <button id="account_button" class="header_menu_button">Account</button>
            <button id="friends_requests" class="header_menu_button" data-url="{% url 'accounts:friendship_requests' %}">Friend's requests</button>
        </div>
    </nav>
</header>